# Site settings
title: Yafei Ou
baseurl: ""
url: "https://yafeiou.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Yafei Ou
  desc:
  email: ou.y.ac@m.titech.ac.jp
  selfie: assets/img/1.jpg

# social
social:
  email: true
  github: yafeiou
  google_plus:
  linkedin:
  default_txt: "Follow On"
  orcid: 0000-0001-7510-0813
  google-scholar: 2SyrQ1oAAAAJ

email:
  Ou: oygrallen@gmail.com
  Ambalathankandy: prasoon.ak@ist.hokudai.ac.jp
  Ikebe: ikebe@ist.hokudai.ac.jp
  Kamishima: ktamotamo2@hs.hokudai.ac.jp
  Wang: haolin.wang.k3@elms.hokudai.ac.jp
  Takamaeda: shinya@is.s.u-tokyo.ac.jp
  Motomura: motomura@artic.iir.titech.ac.jp
  Asai: asai@ist.hokudai.ac.jp

link:
  Ambalathankandy: https://researchers.general.hokudai.ac.jp/profile/en.42a8ea09cd4ba903520e17560c007669.html
  Ikebe: https://researchmap.jp/read0116849
  Kamishima: https://kamishima.hs-hokudai.jp/e_index.html
  Takamaeda: https://sites.google.com/site/shinyaty/home
  Motomura: http://www.artic.iir.titech.ac.jp/wp/en/people/
  Asai: http://lalsie.ist.hokudai.ac.jp/~asai/en/
  Suzuki: https://suzukilab.first.iir.titech.ac.jp/members/kenji-suzuki/
  Gong: https://faculty.swjtu.edu.cn/gongxun

units:
  HU:
    name: Hokkaido University
  Todai:
    name: The University of Tokyo
  TIT:
    name: Tokyo Institute of Technology
  Nihon:
    name: Nihon University
  Keio:
    name: Keio University
  NCC:
    name: National Cancer Center
  SWJTU:
    name: Southwest Jiaotong University

journal:
  Tcsvt:
    name: IEEE Transactions on Circuits and Systems for Video Technology
    IF: 8.3
  Jbhi:
    name: IEEE Journal of Biomedical and Health Informatics
    IF: 6.7
  Cmig:
    name: Computerized Medical Imaging and Graphics
    IF: 5.4
  Isbi:
    name: IEEE International Symposium on Biomedical Imaging (ISBI)
  24miccai:
    name: the 27th International Conference on Medical Image Computing and Computer Assisted Intervention (MICCAI 2024)
    rate: 30%
  24bibm:
    name: 2024 IEEE International Conference on Bioinformatics and Biomedicine (IEEE BIBM 2024)
    rate: 22%
  25aaai:
    name: The 39th Annual AAAI Conference on Artificial Intelligence (AAAI 2025)
    rate: 23.4%
  Bmeicon:
    name: Biomedical Engineering International Conference (BMEiCON)

awards:
  - name: 2023 IEEE Sapporo Young Professionals Best Paper Award
    organizer: IEEE Sapporo Young Professionals
    time: July 2023
    link: https://r10.ieee.org/sapporo-yp/2023/07/31/2023-ieee-sapporo-yp-awards%e3%81%ae%e9%81%b8%e8%80%83%e7%b5%90%e6%9e%9c%e3%81%ae%e7%99%ba%e8%a1%a8/
  - name: Featured Article (Top 7%)
    organizer: IEEE Journal of Biomedical and Health Informatics
    time: January 2023
    link: https://www.embs.org/jbhi/articles/special-issue-on-large-scale-medical-image-and-video-analytics-for-clinical-decision-support/
  - name: Cover Article of Special Issue (1/12)
    organizer: IEEE Journal of Biomedical and Health Informatics
    time: January 2023
    link: https://www.embs.org/jbhi/articles/special-issue-on-large-scale-medical-image-and-video-analytics-for-clinical-decision-support/
#  - name: Bronze Award
#    organizer: 76th Annual Meeting of the Japanese Society of Radiological Technology
#    time: April 2020
#  - name: Excellent Student Award
#    organizer: 76th Annual Meeting of the Japanese Society of Radiological Technology
#    time: April 2020
#  - name: Meritorious Winner (No. 50124) (Top 7%)
#    organizer: Mathematical Contest in Modeling (MCM)
#    time: April 2016


# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Permalinks
enabled: true
permalink: /:year-:month-:day/:title
paginate_path: "page:num/"
#paginate_path: ['page:num/', 'publications/page:num/']
paginate: 50
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "README.md"
future: true

remote_theme: chesterhow/tale

plugins:
  - jekyll-paginate
  - jekyll-remote-theme